name: brival_recruitment_task
description: "May the Force be with you"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.8.1'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  auto_route: ^10.1.0+1
  dio: ^5.8.0+1
  retrofit: ^4.6.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  device_preview: ^1.3.1
  get_it: ^8.0.3
  injectable: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  injectable_generator: ^2.7.0
  auto_route_generator: ^10.1.0
  json_serializable: ^6.9.5
  freezed: ^3.1.0
  retrofit_generator: ^9.7.0
  mockito: ^5.4.6
  bloc_test: ^10.0.0


flutter:
  uses-material-design: true