// Mocks generated by Mockito 5.4.6 from annotations
// in brival_recruitment_task/test/remote/people_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:brival_recruitment_task/features/people/data/models/person_model.dart'
    as _i3;
import 'package:brival_recruitment_task/features/people/data/models/swapi_response_model.dart'
    as _i2;
import 'package:brival_recruitment_task/features/people/data/remote/services/people_api_service.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSwapiResponseModel_0 extends _i1.SmartFake
    implements _i2.SwapiResponseModel {
  _FakeSwapiResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePersonModel_1 extends _i1.SmartFake implements _i3.PersonModel {
  _FakePersonModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PeopleApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeopleApiService extends _i1.Mock implements _i4.PeopleApiService {
  MockPeopleApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.SwapiResponseModel> getPeople() =>
      (super.noSuchMethod(
            Invocation.method(#getPeople, []),
            returnValue: _i5.Future<_i2.SwapiResponseModel>.value(
              _FakeSwapiResponseModel_0(
                this,
                Invocation.method(#getPeople, []),
              ),
            ),
          )
          as _i5.Future<_i2.SwapiResponseModel>);

  @override
  _i5.Future<_i3.PersonModel> getPerson(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPerson, [id]),
            returnValue: _i5.Future<_i3.PersonModel>.value(
              _FakePersonModel_1(this, Invocation.method(#getPerson, [id])),
            ),
          )
          as _i5.Future<_i3.PersonModel>);

  @override
  _i5.Future<dynamic> getPeopleRaw() =>
      (super.noSuchMethod(
            Invocation.method(#getPeopleRaw, []),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);
}
